name: CHAP_giwaxs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - chessanalysispipeline
  - nexpy==2.0.0
  - pip==25.3
  - pyfai==2025.12.1
  - pydantic==2.7.3
  - pip:
    - certif-pyspec==1.5.3
    - chess-scanparsers
