name: CHAP_hdrm
channels:
  - conda-forge
  - hexrd
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - chessanalysispipeline
  - hexrd==0.9.11
  - mpi4py==4.1.1
  - nexpy==2.0.0
  - pip==25.3
  - pydantic==2.7.3
  - pyfai==2025.12.1
  - scikit-image==0.25.2
  - pip:
    - certif-pyspec==1.5.3
    - chess-scanparsers
