name: CHAP_tomo
channels:
  - conda-forge
  - astra-toolbox
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - astra-toolbox==2.4.1
  - chessanalysispipeline
  - fabio==2025.10.0
  - lmfit==1.3.4
  - matplotlib==3.10.8
  - mpi4py==4.1.1
  - nexpy==2.0.0
  - pyfai==2025.12.1
  - scipy==1.15.2
  - pip==25.3
  - pydantic==2.7.3
  - requests==2.32.5
  - sympy==1.14.0
  - tomopy==1.15.3
  - pip:
    - certif-pyspec==1.5.3
    - chess-scanparsers
