name: CHAP_edd
channels:
  - conda-forge
  - hexrd
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - asteval==1.0.8
  - chessanalysispipeline
  - hexrd==0.9.4
  - lmfit==1.3.4
  - matplotlib==3.10.8
  - mpi4py==4.1.1
  - nexpy==2.0.0
  - nexusformat==2.0.0
  - pip==25.3
  - pydantic==2.12.5
  - requests==2.32.5
  - scipy==1.15.2
  - sympy==1.14.0
  - pip:
    - certif-pyspec==1.5.3
    - chess-scanparsers
