title: hollow_pyramid
station: id3a
experiment_type: TOMO
sample:
  name: hollow_pyramid
spec_scans:
- spec_file: ../data/hollow_pyramid/spec.log
  scan_numbers: [3, 4, 5]
independent_dimensions:
- label: rotation_angles
  units: degrees
  data_type: scan_column
  name: theta
- label: x_translation
  units: mm
  data_type: smb_par
  name: ramsx
- label: z_translation
  units: mm
  data_type: smb_par
  name: ramsz
