name: Deploy Sphinx documentation to Pages

on:
  push:
    tags:
    - v*.*.*
#on:
#  push:
#    branches:
#    - docs

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update docs configuration with version (tag) name
      run: |
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" setup.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" CHAP/__init__.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/conf.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/installation.md

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        environment-file: docs/environment.yml
        auto-activate: true
        activate-environment: sphinx
        conda-remove-defaults: true
        use-mamba: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx-math-dollar
        pip install sphinx-rtd-theme
        pip install myst-parser
        #pip install autodoc_pydantic

    - name: Install package
      run: |
        pip install -e .
        conda list

    - name: Generate .rst files with sphinx-apidoc
      run: |
        sphinx-apidoc --tocfile api_documentation -o docs CHAP CHAP/hdrm CHAP/inference CHAP/sin2psi CHAP/test

    - name: Build Sphinx HTML documentation
      run: |
        make clean
        make html
      working-directory: ./docs

    - name: List generated files
      run: |
        pwd
        ls -lha
        find ./docs/_build/html -type f

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html

