name: Deploy Sphinx documentation to Pages

on:
  push:
    tags:
    - v*.*.*
#on:
#  push:
#    branches:
#    - docs

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update docs configuration with version (tag) name
      run: |
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" setup.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" CHAP/__init__.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/conf.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/installation.md

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.19'

    - name: Install package
      run: |
        grep version setup.py
        python -m pip install --upgrade pip
        pip install -e .

    - name: Install dependencies
      run: |
        pip install -r docs/sphinx_requirements.txt
        pip install -r docs/requirements.txt
        # hexrd not available over pip, needs hexrd channel
        conda config --add channels hexrd
        conda config --show channels
        conda list
        conda install hexrd
        conda config --remove channels hexrd
        # tomopy conflicts over pip
        conda config --show channels
        conda list
        conda install tomopy

    - name: Generate .rst files with sphinx-apidoc
      run: sphinx-apidoc --tocfile api_documentation -o docs CHAP

    - name: Build Sphinx HTML documentation
      run: |
        make clean
        make html
      working-directory: ./docs

    - name: List generated files
      run: |
        pwd
        ls -lha
        find ./docs/_build/html -type f

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html

